/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;

/**
 *
 * @author Jackson Hofmann
 */
public class CreateFseDialogue extends javax.swing.JDialog {

    /**
     * Creates new form CreateDialogue
     */
    public CreateFseDialogue() {
        this.setUndecorated(true);
        initComponents();
    }
    public JLabel getNewFseName()
    {
        return this.newFseName;
    }
    public JButton getSubmit()
    {
        return this.submit;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        newFseName = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        streetField = new javax.swing.JTextField();
        streetLabel = new javax.swing.JLabel();
        hoursField = new javax.swing.JFormattedTextField();
        hoursLabel = new javax.swing.JLabel();
        extraInfo = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        houseNumLabel = new javax.swing.JLabel();
        houseNumField = new javax.swing.JFormattedTextField();
        stateLabel = new javax.swing.JLabel();
        stateField = new javax.swing.JFormattedTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        zipcodeLabel = new javax.swing.JLabel();
        zipCodeField = new javax.swing.JFormattedTextField();
        cityLabel = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(420, 275));
        setMinimumSize(new java.awt.Dimension(420, 275));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(420, 275));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        newFseName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newFseName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newFseName.setLabelFor(this);
        newFseName.setText("FSE Name");
        newFseName.setMaximumSize(new java.awt.Dimension(400, 22));
        newFseName.setMinimumSize(new java.awt.Dimension(400, 22));
        newFseName.setPreferredSize(new java.awt.Dimension(400, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(newFseName, gridBagConstraints);

        submit.setText("Submit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(submit, gridBagConstraints);

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(cancel, gridBagConstraints);

        streetField.setColumns(15);
        streetField.setToolTipText("100 University Drive, State College, PA 16801");
        streetField.setMaximumSize(new java.awt.Dimension(220, 20));
        streetField.setMinimumSize(new java.awt.Dimension(220, 20));
        streetField.setPreferredSize(new java.awt.Dimension(220, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(streetField, gridBagConstraints);

        streetLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        streetLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        streetLabel.setLabelFor(streetField);
        streetLabel.setText("Street: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(streetLabel, gridBagConstraints);

        hoursField.setColumns(20);
        try {
            hoursField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####~####-####~####-####~####-####~####-####~####-####~####-####~")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hoursField.setToolTipText("Sunday - Saturday with \"~\" separating days");
        hoursField.setMaximumSize(new java.awt.Dimension(200, 20));
        hoursField.setMinimumSize(new java.awt.Dimension(200, 20));
        hoursField.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(hoursField, gridBagConstraints);

        hoursLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hoursLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hoursLabel.setLabelFor(hoursField);
        hoursLabel.setText("Hours: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(hoursLabel, gridBagConstraints);

        extraInfo.setDisplayedMnemonic('e');
        extraInfo.setLabelFor(this);
        extraInfo.setText("Hover over fields for input info");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        getContentPane().add(extraInfo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        getContentPane().add(filler2, gridBagConstraints);

        houseNumLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        houseNumLabel.setLabelFor(houseNumField);
        houseNumLabel.setText("House Number: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(houseNumLabel, gridBagConstraints);

        houseNumField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        houseNumField.setMaximumSize(new java.awt.Dimension(50, 20));
        houseNumField.setMinimumSize(new java.awt.Dimension(50, 20));
        houseNumField.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(houseNumField, gridBagConstraints);

        stateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stateLabel.setLabelFor(stateField);
        stateLabel.setText("State: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(stateLabel, gridBagConstraints);

        try {
            stateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        stateField.setMaximumSize(new java.awt.Dimension(25, 20));
        stateField.setMinimumSize(new java.awt.Dimension(25, 20));
        stateField.setPreferredSize(new java.awt.Dimension(25, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(stateField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        getContentPane().add(filler3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        getContentPane().add(filler4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        getContentPane().add(filler5, gridBagConstraints);

        zipcodeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zipcodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        zipcodeLabel.setLabelFor(zipCodeField);
        zipcodeLabel.setText("Zipcode: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(zipcodeLabel, gridBagConstraints);

        try {
            zipCodeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        zipCodeField.setMaximumSize(new java.awt.Dimension(50, 20));
        zipCodeField.setMinimumSize(new java.awt.Dimension(50, 20));
        zipCodeField.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(zipCodeField, gridBagConstraints);

        cityLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cityLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cityLabel.setLabelFor(cityField);
        cityLabel.setText("City: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(cityLabel, gridBagConstraints);

        cityField.setMaximumSize(new java.awt.Dimension(100, 20));
        cityField.setMinimumSize(new java.awt.Dimension(100, 20));
        cityField.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(cityField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        getContentPane().add(filler6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        getContentPane().add(filler7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 13;
        getContentPane().add(filler8, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel extraInfo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JFormattedTextField hoursField;
    private javax.swing.JLabel hoursLabel;
    private javax.swing.JFormattedTextField houseNumField;
    private javax.swing.JLabel houseNumLabel;
    private javax.swing.JLabel newFseName;
    private javax.swing.JFormattedTextField stateField;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField streetField;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JButton submit;
    private javax.swing.JFormattedTextField zipCodeField;
    private javax.swing.JLabel zipcodeLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cancel
     */
    public javax.swing.JButton getCancel() {
        return cancel;
    }

    /**
     * @param cancel the cancel to set
     */
    public void setCancel(javax.swing.JButton cancel) {
        this.cancel = cancel;
    }
    /**
     * @return the hoursField
     */
    public javax.swing.JFormattedTextField getHoursField() {
        return hoursField;
    }

    /**
     * @param hoursField the hoursField to set
     */
    public void setHoursField(javax.swing.JFormattedTextField hoursField) {
        this.hoursField = hoursField;
    }

    /**
     * @return the hoursLabel
     */
    public javax.swing.JLabel getHoursLabel() {
        return hoursLabel;
    }

    /**
     * @param hoursLabel the hoursLabel to set
     */
    public void setHoursLabel(javax.swing.JLabel hoursLabel) {
        this.hoursLabel = hoursLabel;
    }

    /**
     * @param newFseName the newFseName to set
     */
    public void setNewFseName(javax.swing.JLabel newFseName) {
        this.newFseName = newFseName;
    }

    /**
     * @param submit the submit to set
     */
    public void setSubmit(javax.swing.JButton submit) {
        this.submit = submit;
    }

    /**
     * @return the houseNumField
     */
    public javax.swing.JFormattedTextField getHouseNumField() {
        return houseNumField;
    }

    /**
     * @param houseNumField the houseNumField to set
     */
    public void setHouseNumField(javax.swing.JFormattedTextField houseNumField) {
        this.houseNumField = houseNumField;
    }

    /**
     * @return the houseNumLabel
     */
    public javax.swing.JLabel getHouseNumLabel() {
        return houseNumLabel;
    }

    /**
     * @param houseNumLabel the houseNumLabel to set
     */
    public void setHouseNumLabel(javax.swing.JLabel houseNumLabel) {
        this.houseNumLabel = houseNumLabel;
    }

    /**
     * @return the stateField
     */
    public javax.swing.JFormattedTextField getStateField() {
        return stateField;
    }

    /**
     * @param stateField the stateField to set
     */
    public void setStateField(javax.swing.JFormattedTextField stateField) {
        this.stateField = stateField;
    }

    /**
     * @return the stateLabel
     */
    public javax.swing.JLabel getStateLabel() {
        return stateLabel;
    }

    /**
     * @param stateLabel the stateLabel to set
     */
    public void setStateLabel(javax.swing.JLabel stateLabel) {
        this.stateLabel = stateLabel;
    }

    /**
     * @return the streetField
     */
    public javax.swing.JTextField getStreetField() {
        return streetField;
    }

    /**
     * @param streetField the streetField to set
     */
    public void setStreetField(javax.swing.JTextField streetField) {
        this.streetField = streetField;
    }

    /**
     * @return the streetLabel
     */
    public javax.swing.JLabel getStreetLabel() {
        return streetLabel;
    }

    /**
     * @param streetLabel the streetLabel to set
     */
    public void setStreetLabel(javax.swing.JLabel streetLabel) {
        this.streetLabel = streetLabel;
    }

    /**
     * @return the zipCodeField
     */
    public javax.swing.JFormattedTextField getZipCodeField() {
        return zipCodeField;
    }

    /**
     * @param zipCodeField the zipCodeField to set
     */
    public void setZipCodeField(javax.swing.JFormattedTextField zipCodeField) {
        this.zipCodeField = zipCodeField;
    }

    /**
     * @return the zipcodeLabel
     */
    public javax.swing.JLabel getZipcodeLabel() {
        return zipcodeLabel;
    }

    /**
     * @param zipcodeLabel the zipcodeLabel to set
     */
    public void setZipcodeLabel(javax.swing.JLabel zipcodeLabel) {
        this.zipcodeLabel = zipcodeLabel;
    }

    /**
     * @return the cityField
     */
    public javax.swing.JTextField getCityField() {
        return cityField;
    }

    /**
     * @param cityField the cityField to set
     */
    public void setCityField(javax.swing.JTextField cityField) {
        this.cityField = cityField;
    }

    /**
     * @return the cityLabel
     */
    public javax.swing.JLabel getCityLabel() {
        return cityLabel;
    }

    /**
     * @param cityLabel the cityLabel to set
     */
    public void setCityLabel(javax.swing.JLabel cityLabel) {
        this.cityLabel = cityLabel;
    }
}
